TOOLS-2854 Add container test utils
aerospike/tools-common-go pull request #12
Opened 2024-02-14 23:06 UTC by jdogmcsteezy

2024-02-20 17:26 UTC, dwelch-spike requested changes
See comments. Content looks good but if the Go client isn't updated I can't use this in the backup library.

2024-02-20 17:44 UTC, jdogmcsteezy commented on testutils/containers.go
> +	"github.com/aerospike/aerospike-client-go/v6"
Ill update it. Are you saying that two versions of the go client can't co-exist at one time?

2024-02-20 18:13 UTC, dwelch-spike commented on testutils/containers.go
> +	"github.com/aerospike/aerospike-client-go/v6"
Unfortunately it seems like it. I get GRPC related build errors when I try building with v6 and v7 in the same project.

2024-02-20 20:18 UTC, jdogmcsteezy commented on testutils/containers.go
> +var configTemplate = fmt.Sprintf(`
I think we might want to require the user pass in their own template rather than change our global value

2024-02-20 21:49 UTC, dwelch-spike commented on testutils/containers.go
> +var configTemplate = fmt.Sprintf(`
I meant "configTemplate"

2024-02-20 21:50 UTC, dwelch-spike commented on testutils/containers.go
> +var configTemplate = fmt.Sprintf(`
Ooops misread that

2024-02-20 21:50 UTC, dwelch-spike commented on testutils/containers.go
> +var configTemplate = fmt.Sprintf(`
IMO it's fine either way. This is a test library so I'm not too concerned about issues with global variables.

2024-02-21 00:16 UTC, dwelch-spike commented on testutils/containers.go
> +var configTemplate = fmt.Sprintf(`
This can be changed later, merging...

2024-02-21 00:16 UTC, dwelch-spike approved these changes
LGTM

2024-02-21 00:17 UTC, merged